openapi: 3.0.3                # REQUIRED: Tells the tool which grammar rules to use.
info:
  title: The Social Network API    # This appears as the BIG HEADER on the webpage.
  version: 1.0.0                   # Helps us track changes (e.g., v1.1, v2.0).
  description: |                   # The "|" allows multi-line text below.
    API for the ft_transcendence social network project.
    Managed by dcingoz.
servers:
  - url: http://localhost:5067     # The base URL where our C# backend lives.
    description: Local Development (HTTP)
  - url: https://localhost:7016 # Your current HTTPS port
    description: Local Development (HTTPS)

paths:
#authentication
#POST /auth/login
#POST /auth/register
#POST /auth/google
#POST /auth/logout
#POST /auth/2fa/enable
#POST /auth/2fa/verify
#POST /auth/2fa/disable
#POST /auth/2fa/generate

#files
#+--GET /files/{fileId}
#+--POST /files
#+--DELETE /files/{fileId}

##friends
#+--#GET /friends/list
#+--#POST /friends/{targetUserId}
#+--#DELETE /friends/{friendUserId}
#+--#GET /friends/requests
#+--#POST /friends/requests/{requestId}/accept
#+--#POST /friends/requests/{requestId}/decline

#posts
#+-#GET /posts/{postId}
#+-#DELETE /posts/{postId}
#+-#POST /posts

#+-#POST /posts/{postId}/likes
#+-#DELETE /posts/{postId}/likes

#+-#POST /posts/{postId}/comments
#+-#DELETE /posts/{postId}/comments/{commentId}

#posts profile
#--#GET /posts/{postId}/likes?take=20&cursor=<nextCursor>
#--#GET /posts/{postId}/comments?take=20&cursor=<nextCursor>
#--#GET /posts/me?take=20&cursor=<nextCursor>
#--#GET /posts/by-userId/{targetUserId}?take=20&cursor=<nextCursor>

#posts feed
#--#GET /posts/feed?take=20&cursor=<nextCursor>

#profile
#+--#GET /profile/me
#+--#GET /profile/{userId}
#+--#PATCH /profile/me
#+--#PATCH /profile/password
#+--#DELETE /me

#notifications
#GET notifications/list

#chat
#GET chat/conversations
#GET chat/{userId}/messages


#This is a maybe feature
#admin (Protected: Admins only)
#GET admin/users
#PATCH admin/users/{id}/role
#POST admin/users/{id}/ban
#DELETE admin/users/{id}/ban

#API:
#Controller
#
#Application:
#Dto
#Exceptions
#Interfaces
#Services
#
#Domain:
#Entities