namespace Transcendence.Domain.Users;

public sealed class User
{
	public Guid Id { get; private set; }
	public string Username { get; private set; } = default!;
	public string PasswordHash { get; private set; } = default!;
	public string Email { get; private set; } = default!;
	public string FullName { get; private set; } = default!;
	public string? Bio { get; private set; }
	public Guid? AvatarFileId { get; private set; }
	public DateTime CreatedAt { get; private set; }

	public string? GoogleId { get; private set; }

	public string? Role { get; private set; }

#pragma warning disable CS8618
	private User() { }
#pragma warning restore CS8618

	public void SetPasswordHash(string passwordHash)
	{
		//if (string.IsNullOrWhiteSpace(passwordHash)) - do we need this check here? The password hash is generated by the IPasswordHasher, so it should never be empty. If we want to be extra safe, we can add this check, but it might be redundant. For now, let's assume that the IPasswordHasher will always return a valid hash and skip this check.
    		//throw new InvalidOperationException("PasswordHash cannot be empty.");
		PasswordHash = passwordHash;
	}

	public User(Guid id, string username, string email, string fullName, DateTime createdAt) // passworHash is set separately using the SetPasswordHash method, as it emphasizes that the password hash is something that can be changed after the user is created
	{
		Id = id;
		SetUsername(username);
		SetEmail(email);
		SetFullName(fullName);
		CreatedAt = createdAt;
	}

	public User(Guid id, string googleId, string username, string email, string fullName, DateTime createdAt)
	{
		Id = id;
		SetUsername(username);
		SetEmail(email);
		SetFullName(fullName);
		CreatedAt = createdAt;
		GoogleId = googleId;
	}

	public User(Guid id, string username, string email, string fullName, DateTime createdAt, string role)
	{
		Id = id;
		SetUsername(username);
		SetEmail(email);
		SetFullName(fullName);
		CreatedAt = createdAt;
		Role = role;
	}
	public void UpdateDetails(string? fullName = null, string? username = null)
	{
		if (fullName != null) SetFullName(fullName);
		if (username != null) SetUsername(username);
	}

	public void UpdateAvatar(Guid? avatarFileId)
	{
		AvatarFileId = avatarFileId;
	}

	public void UpdateBio(string? bio)
	{
		Bio = bio?.Trim();
		if (Bio == "") Bio = null;
	}

	private void SetFullName(string value)
	{
		var v = value.Trim();
		if (v.Length == 0) throw new InvalidOperationException("FullName cannot be empty.");//max length check? Best practice: important rules should be enforced before DB too.
		FullName = v;
	}

	private void SetUsername(string value)
	{
		var v = value.Trim();
		if (v.Length == 0) throw new InvalidOperationException("Username cannot be empty.");//max length check? Best practice: important rules should be enforced before DB too.
		Username = v;
	}

	private void SetEmail(string value)
	{
		var v = value.Trim().ToLowerInvariant();
		if (v.Length == 0) throw new InvalidOperationException("Email cannot be empty.");//should we add email validation?
		Email = v;
	}
}
